apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ldap-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
      - name: ldap-container
        image: master.cloud.com:5000/ldap
        ports:
        - name: ldap-port
          containerPort: 8181
        - name: search-port
          containerPort: 389
---
apiVersion: v1
kind: Service
metadata:
  name: ldap
spec:
  type: NodePort
  ports:
  - port: 8181
    nodePort: 30340
    targetPort: 8181
    protocol: TCP
    name: ldap
  - port: 389
    nodePort: 30341
    targetPort: 389
    protocol: TCP
    name: search
  selector:
    app: ldap

